# Generated by Django 4.0.6 on 2022-09-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="default_town_or_city",
            new_name="default_city",
        ),
    ]
