# Generated by Django 4.0.6 on 2022-09-19 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="town_or_city",
            new_name="city",
        ),
    ]
