# Generated by Django 4.0.6 on 2022-09-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0005_order_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="grand_total",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=5
            ),
        ),
    ]
