# Generated by Django 4.0.6 on 2022-09-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeja",
            name="name",
            field=models.CharField(default="mypic", max_length=25),
            preserve_default=False,
        ),
    ]
