# Generated by Django 4.0.6 on 2022-09-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_meeja_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Meeja",
        ),
    ]
