# Generated by Django 4.0.6 on 2022-09-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testimonials", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testimonial",
            name="image",
        ),
        migrations.AddField(
            model_name="testimonial",
            name="image_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="testimony_title",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
