# Generated by Django 4.0.6 on 2022-09-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "testimonials",
            "0002_remove_testimonial_image_testimonial_image_url_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testimonial",
            name="image_url",
        ),
        migrations.AddField(
            model_name="testimonial",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="ot4u"),
        ),
    ]
