# Generated by Django 4.0.6 on 2022-09-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "testimonials",
            "0003_remove_testimonial_image_url_testimonial_image",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="testimony",
            field=models.TextField(),
        ),
    ]
