# Generated by Django 4.0.6 on 2022-09-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_number",
            field=models.CharField(editable=False, max_length=8),
        ),
    ]
