# Generated by Django 4.0.6 on 2022-09-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_booking_booking_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
