# Generated by Django 4.0.6 on 2022-09-10 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Style",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=254)),
                ("equipment", models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Therapy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=254)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=0, max_digits=3)),
                (
                    "image_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                (
                    "course_sessions",
                    models.PositiveIntegerField(
                        editable=False,
                        help_text="The recommended number of sessions for this particular therapy.",
                    ),
                ),
                ("location", models.CharField(max_length=254)),
                (
                    "extra_requirements",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "style",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="therapy.style",
                    ),
                ),
            ],
        ),
    ]
