# Generated by Django 4.0.6 on 2022-09-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapy", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="therapy",
            options={"verbose_name_plural": "Therapies"},
        ),
        migrations.AlterField(
            model_name="style",
            name="equipment",
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name="therapy",
            name="location",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
