# Generated by Django 4.0.6 on 2022-09-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "therapy",
            "0002_alter_therapy_options_alter_style_equipment_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapy",
            name="course_sessions",
            field=models.PositiveIntegerField(
                help_text="The recommended number of sessions for this particular therapy."
            ),
        ),
    ]
