# Generated by Django 4.0.6 on 2022-09-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapy", "0004_remove_therapy_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapy",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="ot4u"),
        ),
    ]
