# Generated by Django 4.0.6 on 2022-09-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapy", "0005_alter_therapy_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapy",
            name="course_sessions",
            field=models.PositiveIntegerField(
                help_text="The recommended number of         sessions for this particular therapy."
            ),
        ),
    ]
