# Generated by Django 4.0.6 on 2022-09-25 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("therapy", "0006_alter_therapy_course_sessions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapy",
            name="style",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="therapy.style",
            ),
            preserve_default=False,
        ),
    ]
